"""Ajout champ localisation

Revision ID: acd0ef1f6477
Revises: 
Create Date: 2025-07-07 14:51:14.427930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acd0ef1f6477'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trash_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('localisation', sa.String(length=120), nullable=True))
        batch_op.drop_column('location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trash_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=120), nullable=True))
        batch_op.drop_column('localisation')

    # ### end Alembic commands ###
